"""Export assets into a Godot 4 project.

The exporter first builds an :class:`ExportPlan` (list of files that would be
written). The UI shows conflicts and asks before overwriting anything;
:meth:`ExportPlan.execute` refuses to overwrite unless explicitly allowed.

Written files per asset (where applicable):

* ``<id>.png`` / ``<id>_<view>.png``        - final sprites
* ``<id>_sheet.png`` + ``<id>_sheet.json``  - sprite sheet + metadata
* ``<id>_frames.tres``                      - Godot ``SpriteFrames`` resource
* ``<id>_tileset.png`` + ``<id>_tileset.tres`` - Godot ``TileSet`` (with terrain)
* ``<id>_<layer>.png``                      - background layers
* ``scripts/pixel_rpg_directional_sprite.gd`` - optional helper script
"""

from __future__ import annotations

import json
import shutil
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable

from pixel_rpg_studio.core.config import read_json
from pixel_rpg_studio.core.errors import ExportConflictError, StudioError
from pixel_rpg_studio.core.paths import safe_filename
from pixel_rpg_studio.project.asset import ROLE_FINAL, Asset
from pixel_rpg_studio.project.asset_types import get_asset_type
from pixel_rpg_studio.spritesheet.builder import SheetMetadata

ROLE_SHEET_META = "sprite_sheet_meta"
ROLE_TILESET_ATLAS = "tileset_atlas"
ROLE_TILESET_META = "tileset_meta"
VIEW_PREFIX = "final_view:"
LAYER_PREFIX = "layer:"

HELPER_SCRIPT_NAME = "pixel_rpg_directional_sprite.gd"
HELPER_SCRIPT = '''# Generated by Pixel RPG Asset Studio.
# Attach to an AnimatedSprite2D whose SpriteFrames were exported by the studio.
# Animations are named "<action>_<direction>" (e.g. "walk_s", "idle_e").
extends AnimatedSprite2D
class_name PixelRPGDirectionalSprite

## Current facing direction: one of s, sw, w, nw, n, ne, e, se
@export var facing: String = "s"
## Current action, e.g. idle, walk, run, attack
@export var action: String = "idle"

const DIRS_8 := ["e", "se", "s", "sw", "w", "nw", "n", "ne"]

func _ready() -> void:
	texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
	_apply()

## Play an action in the current facing direction.
func play_action(new_action: String) -> void:
	action = new_action
	_apply()

## Face along a movement vector (picks the closest exported direction).
func face_vector(v: Vector2) -> void:
	if v.length_squared() < 0.0001:
		return
	var idx := int(round(fposmod(v.angle(), TAU) / (TAU / 8.0))) % 8
	var wanted: String = DIRS_8[idx]
	facing = _closest_available(wanted)
	_apply()

func _closest_available(wanted: String) -> String:
	flip_h = false
	if sprite_frames == null or sprite_frames.has_animation("%s_%s" % [action, wanted]):
		return wanted
	var fallback := {"se": "e", "ne": "e", "sw": "w", "nw": "w", "e": "w", "w": "e", "n": "s", "s": "n"}
	var alt: String = fallback.get(wanted, "s")
	if sprite_frames.has_animation("%s_%s" % [action, alt]):
		flip_h = wanted in ["e", "se", "ne"] and alt.begins_with("w")
		return alt
	return "s"

func _apply() -> void:
	if sprite_frames == null:
		return
	var anim_name := "%s_%s" % [action, facing]
	if not sprite_frames.has_animation(anim_name):
		anim_name = action
	if sprite_frames.has_animation(anim_name):
		play(anim_name)
'''


@dataclass
class ExportFile:
    target: str  # path relative to the export root (posix)
    source: Path | None = None
    content: str | None = None
    kind: str = "file"


@dataclass
class ExportPlan:
    root: Path
    files: list[ExportFile] = field(default_factory=list)
    notes: list[str] = field(default_factory=list)

    def target_path(self, f: ExportFile) -> Path:
        return self.root / f.target

    def conflicts(self) -> list[str]:
        return [f.target for f in self.files if self.target_path(f).exists()]

    def execute(self, overwrite: bool = False) -> list[Path]:
        conflicts = self.conflicts()
        if conflicts and not overwrite:
            raise ExportConflictError(conflicts)
        written = []
        for f in self.files:
            dest = self.target_path(f)
            dest.parent.mkdir(parents=True, exist_ok=True)
            if f.source is not None:
                shutil.copyfile(f.source, dest)
            else:
                dest.write_text(f.content or "", encoding="utf-8", newline="\n")
            written.append(dest)
        return written


def is_godot_project(path: Path) -> bool:
    return (Path(path) / "project.godot").is_file()


def godot_project_name(path: Path) -> str:
    try:
        for line in (Path(path) / "project.godot").read_text(encoding="utf-8").splitlines():
            if line.startswith("config/name="):
                return line.split("=", 1)[1].strip().strip('"')
    except OSError:
        pass
    return Path(path).name


def _res(subdir: str, *parts: str) -> str:
    rel = "/".join(p.strip("/") for p in (subdir, *parts) if p and p.strip("/"))
    return f"res://{rel}"


def spriteframes_tres(sheet_res_path: str, meta: SheetMetadata) -> str:
    """Godot 4 SpriteFrames resource using AtlasTextures into one sheet."""
    subs: list[str] = []
    anims: list[str] = []
    sub_id = 0
    for anim in meta.animations:
        frame_entries = []
        for fr in anim.frames:
            sub_id += 1
            sid = f"AtlasTexture_{sub_id}"
            subs.append(
                f'[sub_resource type="AtlasTexture" id="{sid}"]\n'
                f'atlas = ExtResource("1_sheet")\n'
                f"region = Rect2({fr.x}, {fr.y}, {fr.w}, {fr.h})\n"
            )
            frame_entries.append(f'{{\n"duration": 1.0,\n"texture": SubResource("{sid}")\n}}')
        anims.append(
            "{\n"
            f'"frames": [{", ".join(frame_entries)}],\n'
            f'"loop": {"true" if anim.loop else "false"},\n'
            f'"name": &"{anim.name}",\n'
            f'"speed": {float(anim.fps)}\n'
            "}"
        )
    header = f'[gd_resource type="SpriteFrames" load_steps={len(subs) + 2} format=3]\n\n'
    ext = f'[ext_resource type="Texture2D" path="{sheet_res_path}" id="1_sheet"]\n\n'
    body = "\n".join(subs)
    resource = f"\n[resource]\nanimations = [{', '.join(anims)}]\n"
    return header + ext + body + resource


def tileset_tres(texture_res_path: str, tile_size: int, atlas_columns: int, atlas_rows: int,
                 tiles_meta: list[dict] | None = None, terrain_names: tuple[str, str] = ("Base", "Overlay"),
                 terrain_colors: tuple[str, str] = ("Color(0.35, 0.6, 0.3, 1)", "Color(0.6, 0.45, 0.3, 1)")) -> str:
    """Godot 4 TileSet with one atlas source; with ``tiles_meta`` a match-corners terrain set is added."""
    lines = [
        '[gd_resource type="TileSet" load_steps=3 format=3]',
        "",
        f'[ext_resource type="Texture2D" path="{texture_res_path}" id="1_atlas"]',
        "",
        '[sub_resource type="TileSetAtlasSource" id="TileSetAtlasSource_1"]',
        'texture = ExtResource("1_atlas")',
        f"texture_region_size = Vector2i({tile_size}, {tile_size})",
    ]
    if tiles_meta:
        for t in tiles_meta:
            x, y = t["atlas"]
            lines.append(f"{x}:{y}/0 = 0")
            lines.append(f"{x}:{y}/0/terrain_set = 0")
            lines.append(f"{x}:{y}/0/terrain = {t['terrain']}")
            for corner in ("top_left", "top_right", "bottom_left", "bottom_right"):
                lines.append(f"{x}:{y}/0/terrains_peering_bit/{corner}_corner = {t['corners'][corner]}")
    else:
        for y in range(atlas_rows):
            for x in range(atlas_columns):
                lines.append(f"{x}:{y}/0 = 0")
    lines += ["", "[resource]", f"tile_size = Vector2i({tile_size}, {tile_size})"]
    if tiles_meta:
        lines += [
            "terrain_set_0/mode = 1",  # TileSet.TERRAIN_MODE_MATCH_CORNERS
            f'terrain_set_0/terrain_0/name = "{terrain_names[0]}"',
            f"terrain_set_0/terrain_0/color = {terrain_colors[0]}",
            f'terrain_set_0/terrain_1/name = "{terrain_names[1]}"',
            f"terrain_set_0/terrain_1/color = {terrain_colors[1]}",
        ]
    lines.append('sources/0 = SubResource("TileSetAtlasSource_1")')
    return "\n".join(lines) + "\n"


def plan_asset_export(asset: Asset, export_root: Path, subdir: str = "assets/generated",
                      write_resources: bool = True, write_helpers: bool = True) -> ExportPlan:
    """Plan the export of one asset into ``export_root/subdir/<type folder>/<asset id>/``."""
    asset_type = get_asset_type(asset.type)
    rel_dir = "/".join(p for p in (subdir.strip("/"), asset_type.folder, asset.id) if p)
    plan = ExportPlan(root=Path(export_root))
    base = safe_filename(asset.id)
    outputs = asset.meta.outputs

    def add_copy(role: str, name: str) -> bool:
        src = asset.output_path(role)
        if src is None:
            return False
        plan.files.append(ExportFile(f"{rel_dir}/{name}", source=src, kind="image" if name.endswith(".png") else "data"))
        return True

    add_copy(ROLE_FINAL, f"{base}.png")
    for role in sorted(outputs):
        if role.startswith(VIEW_PREFIX):
            add_copy(role, f"{base}_{safe_filename(role[len(VIEW_PREFIX):])}.png")
        elif role.startswith(LAYER_PREFIX):
            add_copy(role, f"{base}_{safe_filename(role[len(LAYER_PREFIX):])}.png")

    sheet_src = asset.output_path("sprite_sheet")
    meta_src = asset.output_path(ROLE_SHEET_META)
    if sheet_src is not None:
        sheet_name = f"{base}_sheet.png"
        plan.files.append(ExportFile(f"{rel_dir}/{sheet_name}", source=sheet_src, kind="image"))
        if meta_src is not None:
            meta = SheetMetadata.from_dict(read_json(meta_src))
            meta.image = sheet_name
            plan.files.append(ExportFile(f"{rel_dir}/{base}_sheet.json", content=json.dumps(meta.to_dict(), indent=2) + "\n", kind="data"))
            if write_resources:
                plan.files.append(ExportFile(f"{rel_dir}/{base}_frames.tres", content=spriteframes_tres(_res(rel_dir, sheet_name), meta), kind="resource"))
                if write_helpers and asset_type.key == "character":
                    plan.files.append(ExportFile(f"{subdir.strip('/')}/scripts/{HELPER_SCRIPT_NAME}".lstrip("/"), content=HELPER_SCRIPT, kind="script"))

    atlas_src = asset.output_path(ROLE_TILESET_ATLAS)
    if atlas_src is not None:
        atlas_name = f"{base}_tileset.png"
        plan.files.append(ExportFile(f"{rel_dir}/{atlas_name}", source=atlas_src, kind="image"))
        tmeta_path = asset.output_path(ROLE_TILESET_META)
        tmeta = read_json(tmeta_path) if tmeta_path else None
        if write_resources and tmeta:
            plan.files.append(
                ExportFile(
                    f"{rel_dir}/{base}_tileset.tres",
                    content=tileset_tres(
                        _res(rel_dir, atlas_name), int(tmeta["tile_size"]), int(tmeta["columns"]), int(tmeta["rows"]),
                        tmeta.get("terrain_tiles"), tuple(tmeta.get("terrain_names", ("Base", "Overlay"))),
                    ),
                    kind="resource",
                )
            )
    if not plan.files:
        raise StudioError(
            f"'{asset.name}' has no finished output to export yet.",
            hint="Run the generation pipeline (or import an image) and accept a result first.",
            code="nothing_to_export",
        )
    return plan


def merge_plans(plans: Iterable[ExportPlan]) -> ExportPlan:
    plans = list(plans)
    if not plans:
        raise StudioError("Nothing to export.")
    merged = ExportPlan(root=plans[0].root)
    seen: set[str] = set()
    for p in plans:
        for f in p.files:
            if f.target not in seen:
                seen.add(f.target)
                merged.files.append(f)
        merged.notes.extend(p.notes)
    return merged
